project:
  type: website
  render:
    - index.qmd
    - example.qmd
    - demo/

website:
  title: "quarto-link-previews"
  navbar:
    left:
      - href: index.qmd
        text: Docs
      - href: demo/listing.qmd
        text: Listing demo
    right:
      - icon: github
        href: https://github.com/ravila4/quarto-link-previews

format:
  html:
    theme:
      light: flatly
      dark: darkly
    link-external-icon: true

filters:
  - link-previews

extensions:
  link-previews:
    exclude:
      - ".no-previews-here a"
